version: "3.3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123password
